apiVersion: apps/v1
kind: Deployment
metadata:
  name: excuse-generator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excuse-generator
  template:
    metadata:
      labels:
        app: excuse-generator
    spec:
      containers:
      - name: excuse-generator
        image: excuse-generator:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: excuse-generator-service
spec:
  selector:
    app: excuse-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort