apiVersion: apps/v1
kind: Deployment
metadata:
  name: excuse-generator-ng-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excuse-generator-ng
  template:
    metadata:
      labels:
        app: excuse-generator-ng
    spec:
      containers:
      - name: excuse-generator-ng
        image: excuse_generator_ng:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: excuse-generator-ng-service
spec:
  selector:
    app: excuse-generator-ng
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort